In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.datasets import load_iris


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.datasets import load_iris


In [76]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.datasets import load_iris


In [77]:
iris = load_iris()
x = iris.data
y = iris.target
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [78]:
x_train, x_test, y_train, y_test =train_test_split(x,y, test_size = .20, random_state=42)

In [79]:
rf_model=RandomForestClassifier(n_estimators=100, max_depth=None, min_samples_split=2, min_samples_leaf=1, max_features='sqrt', bootstrap=True,random_state=42)

In [80]:
rf_model.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

In [81]:
y_pred= rf_model.predict(x_test)

In [82]:
y_pred_proba = rf_model.predict_proba(x_test)
y_pred_proba

array([[0.  , 0.99, 0.01],
       [1.  , 0.  , 0.  ],
       [0.  , 0.03, 0.97],
       [0.  , 1.  , 0.  ],
       [0.  , 0.87, 0.13],
       [1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  ],
       [0.  , 0.08, 0.92],
       [0.  , 0.86, 0.14],
       [0.  , 1.  , 0.  ],
       [0.  , 0.05, 0.95],
       [1.  , 0.  , 0.  ],
       [0.94, 0.06, 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 0.98, 0.02],
       [0.  , 0.  , 1.  ],
       [0.  , 1.  , 0.  ],
       [0.  , 1.  , 0.  ],
       [0.  , 0.01, 0.99],
       [1.  , 0.  , 0.  ],
       [0.  , 0.08, 0.92],
       [1.  , 0.  , 0.  ],
       [0.  , 0.01, 0.99],
       [0.  , 0.  , 1.  ],
       [0.  , 0.04, 0.96],
       [0.  , 0.06, 0.94],
       [0.  , 0.  , 1.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ]])

In [83]:
predict = rf_model.predict([[5.9, 3. , 5.1, 1.8]])
predict

array([2])

In [84]:
rf_accuracy = accuracy_score(y_test, y_pred)
rf_accuracy

1.0

In [85]:
cm = confusion_matrix(y_test, y_pred)

In [86]:
cm

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]])

In [87]:
cr = classification_report(y_test, y_pred)

In [88]:
cr

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        10\n           1       1.00      1.00      1.00         9\n           2       1.00      1.00      1.00        11\n\n    accuracy                           1.00        30\n   macro avg       1.00      1.00      1.00        30\nweighted avg       1.00      1.00      1.00        30\n'

In [89]:
importances = rf_model.feature_importances_
importances

array([0.10809762, 0.03038681, 0.43999397, 0.42152159])

In [90]:
model_10 = RandomForestClassifier(n_estimators=10, random_state=42)
model_10.fit(x_train, y_train)

pred_10 = model_10.predict(x_test)
print("Accuracy with 10 trees:", accuracy_score(y_test, pred_10))


Accuracy with 10 trees: 1.0


In [91]:
model_200 = RandomForestClassifier(n_estimators=200, random_state=42)
model_200.fit(x_train, y_train)

pred_200 = model_200.predict(x_test)
print("Accuracy with 200 trees:", accuracy_score(y_test, pred_200))


Accuracy with 200 trees: 1.0


In [92]:
model_depth = RandomForestClassifier(
    n_estimators=100,
    max_depth=3,
    random_state=42
)

model_depth.fit(x_train, y_train)
pred_depth = model_depth.predict(x_test)

print("Accuracy with depth=3:", accuracy_score(y_test, pred_depth))


Accuracy with depth=3: 1.0


In [93]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)
dt.fit(x_train, y_train)

dt_pred = dt.predict(x_test)
print("Decision Tree Accuracy:", accuracy_score(y_test, dt_pred))


Decision Tree Accuracy: 1.0


In [94]:
estimation_list = [10,50,100,200]

for n in estimation_list:
  model = RandomForestClassifier(n_estimators=n, random_state=42)
  model.fit(x_train, y_train)

In [95]:
y_prad= model.predict(x_test)

In [96]:
y_prad

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [97]:
accuracy = accuracy_score(y_test, y_prad)

In [98]:
accuracy

1.0

In [99]:
depth_list = [2,5,10,None]

for d in depth_list:
  model = RandomForestClassifier(n_estimators=100, max_depth=d, random_state=42)
  model.fit(x_train, y_train)

In [100]:
y_prad = model.predict(x_test)

In [101]:
accuracy = accuracy_score(y_test, y_prad)

In [102]:
accuracy

1.0

In [103]:
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(x_train, y_train)

importances = model.feature_importances_
importances

array([0.10809762, 0.03038681, 0.43999397, 0.42152159])